// components/HowItWorks.tsx
import { Container, SectionHeading, Card } from '@/components/shared';
import { Upload, MessageSquare, Flame, CheckCircle } from 'lucide-react';

const STEPS = [
  { 
    icon: Upload, 
    stepNumber: "01",
    title: "Upload Project", 
    desc: "Share your live link or staging environment with our community of active product builders." 
  },
  { 
    icon: MessageSquare, 
    stepNumber: "02",
    title: "Get Feedback", 
    desc: "Receive objective ratings and highly specific, structured reviews targeting your UX and performance." 
  },
  { 
    icon: Flame, 
    stepNumber: "03",
    title: "Improve", 
    desc: "Iterate swiftly using centralized bug tickets and custom insight scoreboards generated by peers." 
  },
  { 
    icon: CheckCircle, 
    stepNumber: "04",
    title: "Launch", 
    desc: "Publish to mainstream platforms with confidence, backed by clear engineering validation." 
  },
];

export const HowItWorks = () => (
  <section className="py-24 bg-slate-50/50 relative overflow-hidden border-y border-slate-100">
    <Container>
      
      {/* Centralized Section Header */}
      <SectionHeading 
        title="Engineered for Iteration" 
        subtitle="How LaunchLens guides your product from an early build to a market-ready release." 
        centered 
      />

      {/* Workflow Timeline Container */}
      <div className="relative mt-16 grid grid-cols-1 md:grid-cols-4 gap-8 md:gap-4">
        
        {/* Horizontal Connector Line (Hidden on Mobile viewports) */}
        <div className="hidden md:block absolute top-8 left-12 right-12 h-[2px] bg-gradient-to-r from-[#FF6B35]/30 via-slate-200 to-transparent z-0" />

        {/* Individual Step Render Matrix */}
        {STEPS.map((step, idx) => (
          <div key={idx} className="relative z-10 flex flex-col items-center md:items-start text-center md:text-left px-4 group">
            
            {/* Structural Node Circle */}
            <div className="w-16 h-16 bg-white border border-slate-200/80 rounded-2xl flex items-center justify-center shadow-sm group-hover:shadow-md group-hover:border-[#FF6B35]/40 transition-all duration-300 relative">
              <step.icon className="text-[#FF6B35] transition-transform group-hover:scale-110 duration-300" size={24} />
              
              {/* Discrete Step Number Index Layer */}
              <span className="absolute -top-2.5 -right-2.5 bg-slate-100 border border-slate-200/60 rounded-md text-[10px] font-bold text-slate-500 px-1.5 py-0.5 group-hover:bg-[#FF6B35] group-hover:text-white group-hover:border-transparent transition-colors">
                {step.stepNumber}
              </span>
            </div>

            {/* Mobile Vertical Connector Chevron Indicator */}
            {idx < STEPS.length - 1 && (
              <div className="md:hidden my-4 text-slate-300 font-bold text-xl animate-bounce">
                ↓
              </div>
            )}

            {/* Step Content Card Text Blocks */}
            <div className="mt-6">
              <h3 className="text-lg font-bold text-slate-900 tracking-tight group-hover:text-[#FF6B35] transition-colors duration-200">
                {step.title}
              </h3>
              <p className="mt-2 text-sm text-slate-600 leading-relaxed max-w-xs md:max-w-none">
                {step.desc}
              </p>
            </div>

          </div>
        ))}

      </div>

    </Container>
  </section>
);